config/routes.rb
Rails.application.routes.draw do

  root 'appointments#index'

  resources :appointments
  resources :patients
  resources :doctors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates_presence_of :time

  belongs_to :doctors
  belongs_to :patients
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :appointment

  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  validates_presence_of :first_name
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :appointment

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  validates_presence_of :first_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def index
      @appointments = Appointment.all
    end

    def new
      @appointment = Appointment.new
    end

    def create
      @appointment = Appointment.new(appointment_params)
      if @appointment.save
        flash[:success] = "This appointment is now created"
        redirect_to root_path
      else
        render :new
      end
    end

    def destroy
      appointment = Appointment.find(params[:id])
      appointment.destroy
      flash[:success] = 'Appointment Deleted'
      redirect_to appointment_path(appointment.patient_id)
    end

    private
      def appointment_params
        params.require(:appointment).permit(:patient_id, :doctor_id, :time)
      end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to root_path, notice: 'Doctor was Created'
    else
      render :new
    end
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'doctor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctor_path, notice: 'Doctor was deleted.'
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :schedual)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient, notice: 'patient was Created'
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patient_path, notice: 'patient was deleted.'
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :appointment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_for (appointment) do |f| %>
  <%= f.label :time %>
  <%= f.time_field :time, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<% if @appointments.any? %>
<h2>Here are your appointments</h2>
  <% @appointments.each do |a| %>
    <span>Doctor: <%= Doctor.find(a.doctor_id).last_name %> | Patient: <%= Patient.find(a.patient_id).last_name %></span>
  <% end %>
<% else %>
  <h2>Make a New Appointment</h2>
<% end %>

<%= link_to 'Add a doctor', new_doctor_path %>
<br />
<%= link_to 'Add yourself', new_patient_path %>
<br />
<%= link_to 'Make an Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>When can you do it?</h1>

<%= render 'form', appointment: @appointment %>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :schedual %>
  <%= f.time_field :schedual %>
  <br />
  <%= f.submit %>
<% end %>

app/views/doctors/new.html.erb
<h1>What's up Doc?</h1>

<%= render 'form', doctor: @doctor %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorApp</title>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo">Appointment Maker</a>
          <a href="#" data-activates="mobile" class="button-collapse">
            <i class="material-icons">menu</i>
          </a>
          <ul class="right hide-on-med-and-down">
            <li> <%= link_to 'You', patients_path %> </li>
            <li> <%= link_to 'Doctors', doctors_path %> </li>
            <li> <%= link_to 'Appointment', new_appointment_path %> </li>
          </ul>
          <ul class="side-nav" id="mobile">
            <li> <%= link_to 'You', patients_path %> </li>
            <li> <%= link_to 'Doctors', doctors_path %> </li>
            <li> <%= link_to 'Appointments', new_appointment_path %> </li>
          </ul>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for @doctor do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :appointment %>
  <%= f.time_field :appointment %>
  <br />
  <%= f.submit %>
<% end %>

app/views/patients/new.html.erb
<h1>Patients#new</h1>
<p>Find me in app/views/patients/new.html.erb</p>